language: scala
sudo: required
scala:
  - 2.11.7
addons:
  apt:
    packages: libgmp-dev
install:
  - cd secp256k1
  - ./autogen.sh
  - ./configure --enable-jni --enable-experimental --enable-module-ecdh
  - make
  - sudo cp .libs/libsecp256k1.so /usr/lib
  - cd ../
script: "sbt clean coverage test"
after_success: "sbt coverageReport coveralls"
