language: scala
sudo: required
scala:
  - 2.11.7
install:
  - cd secp256k1
  - ./autogen.sh
  - ./configure
  - sudo make install
script: "sbt clean coverage test"
after_success: "sbt coverageReport coveralls"
